//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNHANSUEntities : DbContext
    {
        public QLNHANSUEntities()
            : base("name=QLNHANSUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_BANGCONG> tb_BANGCONG { get; set; }
        public DbSet<tb_BAOHIEM> tb_BAOHIEM { get; set; }
        public DbSet<tb_CHUCVU> tb_CHUCVU { get; set; }
        public DbSet<tb_CONGTY> tb_CONGTY { get; set; }
        public DbSet<tb_DANTOC> tb_DANTOC { get; set; }
        public DbSet<tb_PHONGBAN> tb_PHONGBAN { get; set; }
        public DbSet<tb_TANGCA> tb_TANGCA { get; set; }
        public DbSet<tb_TONGIAO> tb_TONGIAO { get; set; }
        public DbSet<tb_TRINHDO> tb_TRINHDO { get; set; }
        public DbSet<tb_UNGLUONG> tb_UNGLUONG { get; set; }
        public DbSet<tp_BOPHAN> tp_BOPHAN { get; set; }
        public DbSet<tb_HOPDONG> tb_HOPDONG { get; set; }
        public DbSet<tb_KHENTHUONG_KYLUAT> tb_KHENTHUONG_KYLUAT { get; set; }
        public DbSet<tb_NHANVIEN_DIEUCHUYEN> tb_NHANVIEN_DIEUCHUYEN { get; set; }
        public DbSet<tb_NHANVIEN> tb_NHANVIEN { get; set; }
        public DbSet<tb_NHANVIEN_THOIVIEC> tb_NHANVIEN_THOIVIEC { get; set; }
        public DbSet<tb_NHANVIEN_NANGLUONG> tb_NHANVIEN_NANGLUONG { get; set; }
        public DbSet<tb_LOAICA> tb_LOAICA { get; set; }
        public DbSet<tb_LOAICONG> tb_LOAICONG { get; set; }
        public DbSet<tb_BANGCONG_NHANVIEN_CHITIET> tb_BANGCONG_NHANVIEN_CHITIET { get; set; }
        public DbSet<tb_KYCONG> tb_KYCONG { get; set; }
        public DbSet<tb_KYCONGCHITIET> tb_KYCONGCHITIET { get; set; }
        public DbSet<tb_User> tb_User { get; set; }
    }
}
