//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        public tb_NHANVIEN()
        {
            this.tb_BANGCONG = new HashSet<tb_BANGCONG>();
            this.tb_BAOHIEM = new HashSet<tb_BAOHIEM>();
            this.tb_HOPDONG = new HashSet<tb_HOPDONG>();
            this.tb_KHENTHUONG_KYLUAT = new HashSet<tb_KHENTHUONG_KYLUAT>();
            this.tb_TANGCA = new HashSet<tb_TANGCA>();
            this.tb_UNGLUONG = new HashSet<tb_UNGLUONG>();
        }
    
        public int MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<int> IDPB { get; set; }
        public Nullable<int> IDBP { get; set; }
        public Nullable<int> IDCV { get; set; }
        public Nullable<int> IDTD { get; set; }
        public Nullable<int> IDDT { get; set; }
        public Nullable<int> IDTG { get; set; }
        public Nullable<int> MACTY { get; set; }
        public Nullable<bool> DATHOIVIEC { get; set; }
    
        public virtual ICollection<tb_BANGCONG> tb_BANGCONG { get; set; }
        public virtual ICollection<tb_BAOHIEM> tb_BAOHIEM { get; set; }
        public virtual tb_CHUCVU tb_CHUCVU { get; set; }
        public virtual tb_CONGTY tb_CONGTY { get; set; }
        public virtual ICollection<tb_HOPDONG> tb_HOPDONG { get; set; }
        public virtual ICollection<tb_KHENTHUONG_KYLUAT> tb_KHENTHUONG_KYLUAT { get; set; }
        public virtual tb_PHONGBAN tb_PHONGBAN { get; set; }
        public virtual tb_TRINHDO tb_TRINHDO { get; set; }
        public virtual tp_BOPHAN tp_BOPHAN { get; set; }
        public virtual ICollection<tb_TANGCA> tb_TANGCA { get; set; }
        public virtual ICollection<tb_UNGLUONG> tb_UNGLUONG { get; set; }
    }
}
