//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PHONGBAN
    {
        public tb_PHONGBAN()
        {
            this.tb_NHANVIEN = new HashSet<tb_NHANVIEN>();
        }
    
        public int IDPB { get; set; }
        public string TENPB { get; set; }
    
        public virtual ICollection<tb_NHANVIEN> tb_NHANVIEN { get; set; }
    }
}
